const mongoose = require('mongoose');

const consultationSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  patient_id: { type: String, required: true },
  consultation_type: { type: String, enum: ['initial', 'follow_up'], required: true },
  consultation_date: { type: String, required: true },

  fosa: { type: String },
  fosa_other: { type: String },
  region: { type: String },
  district: { type: String },
  diagnostic_date: { type: String },
  ipp: { type: String },
  personnel: { type: String },
  personnel_remplissant: { type: String },
  poids: { type: String },
  taille: { type: String },
  referred: { type: String },
  referred_from: { type: String },
  referred_from_other: { type: String },
  referred_for: { type: String },

  full_name: { type: String },
  age: { type: String },
  birth_date: { type: String },
  sex: { type: String },
  quartier: { type: String },
  lieu_dit: { type: String },
  address: { type: String },
  emergency_contact_name: { type: String },
  emergency_contact_relation: { type: String },
  emergency_contact_phone: { type: String },
  patient_phone: { type: String },
  patient_phone_number: { type: String },
  lives_with: { type: String },
  vit_avec_patient: { type: String },
  lien_avec_patient: { type: String },
  insurance: { type: String },
  insurance_other: { type: String },
  support_group: { type: String },
  group_name: { type: String },
  appartient_groupe: { type: String },
  nom_groupe_association: { type: String },
  parents: { type: String },
  sibling_rank: { type: String },
  rang_fratrie: { type: String },
  nombre_drepanocytaire_fratrie: { type: String },

  sickle_type: { type: String },
  diagnosis_age: { type: String },
  diagnosis_circumstance: { type: String },
  family_history: { type: String },
  other_medical_history: { type: String },
  autres_antecedents_medicaux: { type: String },
  other_medical_history_details: { type: String },
  previous_surgeries: { type: String },
  interventions_chirurgicales_anterieures: { type: String },
  date_derniere_intervention: { type: String },
  cause_derniere_intervention: { type: String },
  acide_folique_step3: { type: String },
  nombre_crises_vaso: { type: String },
  allergies: { type: String },
  allergies_details: { type: String },

  vocs: { type: String },
  cvo_3_derniers_mois: { type: String },
  hospitalizations: { type: String },
  hospitalisations_3_derniers_mois: { type: String },
  nombre_hospitalisations_3mois: { type: String },
  hospitalization_cause: { type: String },
  longest_hospitalization: { type: String },
  hb_1: { type: String },
  hb_2: { type: String },
  hb_3: { type: String },
  taux_hemoglobine_recent: { type: String },
  taux_hbf_recent: { type: String },
  taux_hbs_recent: { type: String },
  hbf_1: { type: String },
  hbf_2: { type: String },
  hbf_3: { type: String },
  hbs_1: { type: String },
  hbs_2: { type: String },
  hbs_3: { type: String },
  transfusion_reaction: { type: String },
  reaction_types: { type: [String] },
  reaction_type_other: { type: String },
  allo_immunization: { type: String },
  hyperviscosity: { type: String },
  acute_chest_syndrome: { type: String },
  acute_event: { type: String },
  acute_event_details: { type: String },
  stroke: { type: String },
  priapism: { type: String },
  leg_ulcer: { type: String },
  cholecystectomy: { type: String },
  asplenia: { type: String },
  recommended_vaccines: { type: [String] },
  drug_side_effects: { type: String },

  hydroxyurea: { type: String },
  tolerance: { type: String },
  hydroxyurea_reasons: { type: String },
  hydroxyurea_dosage: { type: String },
  posologie_hydroxyurea: { type: String },
  folic_acid: { type: String },
  antibio_prophylaxie: { type: String },
  regular_transfusion: { type: String },
  transfusion_type: { type: String },
  type_transfusion_sanguine: { type: String },
  transfusion_frequency: { type: String },
  frequence_transfusion_3mois: { type: String },
  last_transfusion_date: { type: String },
  autres_traitements_specifiques: { type: String },
  observance: { type: [String] },

  nfs_gb: { type: String },
  nfs_hb: { type: String },
  nfs_pqts: { type: String },
  reticulocytes: { type: String },
  microalbuminuria: { type: String },
  hemolysis: { type: String },
  gs_rh: { type: String },
  imagerie_medical: { type: String },
  ophtalmologie: { type: String },
  consultations_specialisees: { type: String },
  examen_du_jour: { type: String },

  impact_scolaire: { type: String },
  participation_causeries: { type: String },
  suivie_psychologique: { type: String },
  education_therapeutique: { type: String },
  consultation_psychologique: { type: String },
  visite_domicile: { type: String },
  soutien_social: { type: String },
  soutien_social_options: { type: [String] },
  impact_social: { type: String },
  accompagnement_special: { type: String },
  famille_informee: { type: String },
  plan_suivi_personnalise: { type: String },
  date_prochaine_consultation: { type: String },

  examens_avant_consultation: { type: [String] },
  evolution: { type: String },
  education_therapeutique_step8: { type: String },
  date_prochaine_consultation_plan: { type: String },

  commentaires: { type: String },

  created_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now },
});

module.exports = mongoose.model('Consultation', consultationSchema);
