const mongoose = require('mongoose');

const patientSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  numero_identification_unique: { type: String, required: true },
  nom: { type: String, required: true },
  prenom: { type: String, required: true },
  date_naissance: { type: String, required: true },
  age: { type: String, required: true },
  sexe: { type: String, required: true },
  quartier: { type: String, required: true },
  lieu_dit: { type: String, required: true },
  contact_urgence_nom: { type: String, required: true },
  contact_urgence_telephone: { type: String, required: true },
  contact_urgence_relation: { type: String, required: true },
  telephone_patient: { type: String, required: true },
  vit_avec_le_patient: { type: Boolean, required: true },
  lien_avec_patient: { type: String, required: true },
  patient_refere: { type: Boolean, required: true },
  patient_refere_de: { type: String },
  patient_refere_pour: { type: String },
  appartient_a_groupe: { type: Boolean, required: true },
  nom_du_groupe: { type: String },
  rang_dans_fratrie: { type: String },
  nombre_de_drepanocytaires_dans_fratrie: { type: String },
  assurance: { type: String, required: true },
  type_de_drepanocytose: { type: String, required: true },
  age_diagnostic: { type: String, required: true },
  circonstances_du_diagnostic: { type: String, required: true },
  region: { type: String, required: true },
  antecedent_familiaux: { type: String, required: true },
  autres_antecedents_medicaux: { type: String, required: true },
  allergies_connues: { type: Boolean, required: true },
  details_allergies: { type: String },
  groupe_sanguin_rhesus: { type: String, required: true },
  created_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now },
});

module.exports = mongoose.model('Patient', patientSchema);
